### ISSUE TITLE
Review Page Design

### ISSUE THREAD

**Issue by bluek1te** [bluek1te/feed-txstate#3]
Review page design for food rescue path in html

**Comment by steph-long** [comment]
@BenjaminWalkerBond Last week you created a "review" component under rescue/temperature so that I could edit the html/css to make a review page. I don't see the review folder in Visual Studio today.
![screenshot](https://user-images.githubusercontent.com/53979298/63227098-a1849d00-c1a8-11e9-984d-0564fd299cb7.JPG)

**Comment by BenjaminWalkerBond** [comment]
That’s most likely because you didn’t push your changes to github before Phil migrated the project to the public Github repository. If you use github desktop to navigate back to the Texas state enterprise repo, visual studio should replace the review component that is now missing. I suggest making a copy of the files you altered/created, and then placing them in the new repo directory.

**Comment by steph-long** [comment]
I have a review page set up, sort of. Right now, I just have a table and place holder text. I'll need help writing code to "pull" from rescue locations and temperatures that have been entered.
